version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    # environment:
    #   - discovery.type=single-node
    #   - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    depends_on:
      - postgres
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
